### What is NumPy?
- Numpy is called Numerical python
- core of the scientific Python and PyData ecosystems
- The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.
- The NumPy library contains multidimensional array and matrix data structures

### The difference between Numpy Array and python List
- is Fast for creating arrays
- All of the elements in a NumPy array should be homogeneous
- NumPy arrays are faster and more compact than Python lists
- NumPy uses much less memory to store data and it provides a mechanism of specifying the data types.





### Creating Numpy Array using np.array()


In [7]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


### Array filled with 0's

In [8]:
b = np.zeros(2)
print(b)

[0. 0.]


### An array filled with 1’s:

In [9]:
c = np.ones(2)
print(c)

[1. 1.]


### Creating an empty array

In [10]:
# creating an empty array with 2 elements
d = np.empty(2)
print(d)

[1. 1.]


### Creating array with range of elements

In [12]:
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


### Array with evenly spaced intervals

In [13]:
a = np.arange(2,13,2)
print(a)

[ 2  4  6  8 10 12]


### Array with values that are spaced linearly in a specified interval

In [15]:
b = np.linspace(0,20,num=5)
print(b)

[ 0.  5. 10. 15. 20.]


### specifing data type

In [16]:
b = np.ones(4,dtype= np.int64)
print(b)

[1 1 1 1]


In [17]:
b = np.ones(3,dtype="int64")
print(b)

[1 1 1]


In [18]:
b= np.ones(2,dtype = np.int32)
print(b)

[1 1]


### Sorting Elements 
- Sorting an element is simple with np.sort()
- np.sort() returns the copy of the sorted array
- You can specify the axis, kind, and order when you call the function.

In [20]:
# sorting in ascending order
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.sort(arr)
print(arr)

[1 2 3 4 5 6 7 8]


### In addition to sort, which returns a sorted copy of an array, you can use

- argsort, which is an indirect sort along a specified axis,

- lexsort, which is an indirect stable sort on multiple keys,

- searchsorted, which will find elements in a sorted array, and

- partition, which is a partial sort.

##### numpy.argsort(a, axis=- 1, kind=None, order=None)
- a :array_like
- axis : int or None, optional
- kind : {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional
- order : str or list of str, optional

In [22]:
# sorting along axis -1
a =np.array([3, 1, 2])
np.argsort(a)

array([1, 2, 0], dtype=int64)

In [31]:
a = np.array([[3, 1, 2],[3,4,6]])
np.argsort(a,axis=0,kind="stable")

array([[0, 0, 0],
       [1, 1, 1]], dtype=int64)

In [32]:
a = np.array([[3, 1, 2],[3,4,6]])
np.argsort(a,axis=1,kind="stable")

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [33]:
a = np.array([[3, 1, 2],[3,4,6]])
np.argsort(a,axis=-1,kind="stable")

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [34]:
a = np.array([[3, 1, 2],[3,4,6]])
np.argsort(a,axis=1,kind="mergesort")

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [36]:
a = np.array([[3, 1, 2],[3,4,6]],dtype=[('x', '<i4'), ('y', '<i4')])
np.argsort(a,axis=1,kind="mergesort",order=('y','x'))

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [37]:
a = np.array([[3, 1, 2],[3,4,6]],dtype=[('x', '<i4'), ('y', '<i4')])
np.argsort(a,axis=1,kind="mergesort",order=('x','y'))

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

### Concatenating Arrays

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([4,1,1,7,3,4])
np.concatenate((a,b))

array([1, 2, 3, 4, 4, 1, 1, 7, 3, 4])

In [42]:
c = np.array([[3,4,5,1],[4,1,0,1]])
d = np.array([3,4,54,5])
np.concatenate((c,d))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [43]:
c = np.array([[3,4,5,1],[4,1,0,1]])
d = np.array([3,4,54,5])
np.concatenate((c,d),axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [44]:
c = np.array([[3,4,5,1],[4,1,0,1]])
d = np.array([[3,4,54,5]])
np.concatenate((c,d))

array([[ 3,  4,  5,  1],
       [ 4,  1,  0,  1],
       [ 3,  4, 54,  5]])

In [46]:
c = np.array([[3,4,5,1],[4,1,0,1]])
d = np.array([[3,4,54,5]])
np.concatenate((c,d),axis=0)

array([[ 3,  4,  5,  1],
       [ 4,  1,  0,  1],
       [ 3,  4, 54,  5]])

In [47]:
c = np.array([[3,4,5,1],[4,1,0,1]])
d = np.array([[3,4,54,5]])
np.concatenate((c,d),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### The dimension of an Array
- ndarray.ndim will tell you the number of axes, or dimensions, of the array.

In [49]:
# this array has 2 dimensions or axises
arr = np.array([[1,2,3],[34,5,6],[31.5,9,0]])
arr.ndim

2

### The size of an Array
- ndarray.size will tell you the total number of elements of the array
- This is the product of the elements of the array’s shape.

In [50]:
arr.size

9

### The shape of an array
- ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array
- If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3)

In [51]:
arr.shape

(3, 3)