# What is Numpy
- NumPY's main object a homogeneous multidimensional array
- It is a table of elements all of the same type indexed by non negative integers. 
- In numpy the dimensions are called axes


In [1]:
import numpy as np


### Array creation

In [3]:
# np.array() basic
# creating one dimestional array
a = np.array([5,6,7])
a

array([5, 6, 7])

In [4]:
# creating 2d array
a = np.array([[4,5,6],[6,77,2]])
a

array([[ 4,  5,  6],
       [ 6, 77,  2]])

In [8]:
# values all zeros
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# values all 1s
d = np.ones((3,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# values with random
# based the content of the memory
c = np.empty((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# 2D array with ones in the digonal and zeros elsewhere or identity martrix kind
d = np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# convert the input as an array
a = np.asarray([4,5,56,1])
a

array([ 4,  5, 56,  1])

In [16]:
# the difference between np.array() and np.asarray() is np.array() creates the copy by default but np.asarray() will not unless 
# necessary
a  = np.array([[5,3,2,3],[46,7,7,8]],dtype= np.float32)
a 

array([[ 5.,  3.,  2.,  3.],
       [46.,  7.,  7.,  8.]], dtype=float32)

In [17]:
# changed a 
print(np.array(a,dtype= np.float64)is a)

False


In [18]:
b = np.asarray([4,5,56],dtype= np.float32)


In [19]:
print(np.asarray(b,dtype=np.float64)is b)

False


In [20]:
print(np.asarray(a,dtype= np.float32) is a)

True


In [21]:
print(np.asarray(a,dtype= np.float64) is a)

False


In [22]:
# ND array with a sequence of numbers
# arange(start,end,step)
a = np.arange(4,20,2)
a

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
# to get array of with evenspaced interval
# np.linspace(start,end,number of even spaces)
a = np.linspace(2,18,6)
a

array([ 2. ,  5.2,  8.4, 11.6, 14.8, 18. ])

In [24]:
# Attributes of nd array
# np.shape 
# shape indicates the tuples of integer 
a.shape 

(6,)

In [25]:
# np.ndim
# the number of axes(dimenssions) of the array
a.ndim


1

In [26]:
# np.size
# the total number of elements in the array
a.size

6

In [27]:
a.dtype


dtype('float64')

### indexing,slicing and iterating 
- indexing, slicing and iterating of nd array is the same as python lists.

In [5]:
# indexing
a = np.array([[4,9,5],[234,0,2]])
a[0][2]

5

In [7]:
# slicing 
a = np.arange(10)
print(a[2:8:2]) # strarting from 2 upto 8 increasing by 2

[2 4 6]


In [8]:
print(a[2:8]) # starting from 2 upto 8 increasing by 1

[2 3 4 5 6 7]


In [9]:
print(a[2]) # the second index item

2


In [10]:
print(a[2:])

[2 3 4 5 6 7 8 9]


### Change the shape of an array
- gives the array a new shape without changing the data 
- array.reshape(newshape,order )


In [2]:
a = np.arange(10)
b =a.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Broadcasting
- Broadcasting is how numpy treats arrays with different shapes during arithmetic operations

In [3]:
# multiplication on the same shape arrays
# numpy compares two arrays element wise
a = np.array([3,3,5,5])
b = np.array([2,35,1,0])
c = a* b
c

array([  6, 105,   5,   0])

In [4]:
# to arrays are compatible if
# they are equal 
# one of them is is 1 


In [13]:
a = np.array([[3,4,5],[5,4,1],[6,4,1]])
b = np.array([[[3,4,1]]])
c = a*b
a.shape

(3, 3)

In [14]:
b.shape

(1, 1, 3)

In [15]:
c

array([[[ 9, 16,  5],
        [15, 16,  1],
        [18, 16,  1]]])

In [16]:
a = np.array([[3,4,5],[5,4,1],[6,4,1]])
b = np.array([[3,4,1]])
c = a+b
c

array([[6, 8, 6],
       [8, 8, 2],
       [9, 8, 2]])

In [18]:
a = np.array([[3,4,5],[5,4,1],[6,4,1]])
b = np.array([3,4,0])
c = a/b
c

C:\Users\Abraham\AppData\Local\Temp\ipykernel_9296\2505894111.py:3: RuntimeWarning: divide by zero encountered in true_divide
  c = a/b


array([[1.        , 1.        ,        inf],
       [1.66666667, 1.        ,        inf],
       [2.        , 1.        ,        inf]])

In [19]:
a = np.array([[3,4,5],[5,4,1],[6,4,1]])
b = np.array([3,4,1])
c = a -b
c

array([[0, 0, 4],
       [2, 0, 0],
       [3, 0, 0]])

In [20]:
a = np.array([[3,4,5],[5,4,1],[6,4,1]])
b = np.array([[3,4,1],[3,4,5]])
c = a+ b
c

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [21]:
a = np.array([[3,4,5],[5,4,1],[6,4,1]])
b = np.array([3,4])
c = a*b
c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

### Numpy common functions
- ndarray.flat() 
    - a 1D iterator over the array


In [25]:
a = np.array([[4,5,5],[41,2,4,2]])
a



C:\Users\Abraham\AppData\Local\Temp\ipykernel_9296\2645956742.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[4,5,5],[41,2,4,2]])


array([list([4, 5, 5]), list([41, 2, 4, 2])], dtype=object)

In [26]:
# we can't create array like the following
a = np.array([[4,5,5],[41,2,4,3]],dtype = np.float64)
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [30]:

a = np.array([[4,5,5],[41,2,4]])
print(a.flat[:])

[ 4  5  5 41  2  4]


### Transpose
- ndarray.transpose()
   - view of array with axes transposed

In [31]:
a = np.array([[4,2,3],[4,5,1]])
a.T

array([[4, 4],
       [2, 5],
       [3, 1]])

In [32]:
np.transpose(a)

array([[4, 4],
       [2, 5],
       [3, 1]])

### Concatenate 
- join a sequence of arrays along an existing axes
  - numpy.concatenate((a1,a2...),axis =0, out= None)
  - a1 , a2 ... the array must have the same shape except the dimension corrosponding to the axes(the first,by default)
  - axis : the axis where the arrays joined. if the axis is None, the array first flattened before use.default is 0

In [33]:
a = np.arange(6).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [36]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

### Numpy.stack(arrays,axis = 0,out= None)
- join a sequence of arrays along a new axis
- axis parameter speciifies the index of the new axis in the dimesion of the result.
- if the axis is zero it will the first dimension and if it -1 it will the last dimession

In [38]:
a = np.array([9,3])
b = np.array([2,3])
np.stack((a,b),axis=0)

array([[9, 3],
       [2, 3]])

In [39]:
np.stack((a,b),axis=1)

array([[9, 2],
       [3, 3]])

### Numpy.append(arr,values,axis = None)
- append the value to the end of the array

In [48]:
# the array to be appended should match column count
a = np.array([[2,3,4],[1,5,1]])
b = np.append(a,[[3,4]],axis=0)
b.shape

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [41]:
a = np.array([[2,3,4],[1,5,1]])
b = np.append(a,[[3,4,3]],axis=0)
b.shape

(3, 3)

In [42]:
b

array([[2, 3, 4],
       [1, 5, 1],
       [3, 4, 3]])

In [44]:
a = np.array([[2,3,4],[1,5,1]])
b = np.append(a,[[[3,4,2]]],axis=0)
b.shape

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [45]:
# The array will be appended should have the same dimension to the where it will be appended
a = np.array([[2,3,4],[1,5,1]])
b = np.append(a,[2,3,4],axis=0)
b.shape

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [47]:
# if no axis specified the array will be flattened 
a = np.array([[2,3,4],[1,5,1]])
b = np.append(a,[[3,4,2]])
b

array([2, 3, 4, 1, 5, 1, 3, 4, 2])

### Numpy.insert(arr,obj,values,axis = None)
- insert values in the given axis before the given index

In [49]:
a = np.arange(8).reshape(2,4)
b = np.insert(a,2,[7,3],axis=1)
b

array([[0, 1, 7, 2, 3],
       [4, 5, 3, 6, 7]])

In [51]:
a = np.arange(8).reshape(2,4)
b = np.insert(a,2,[[[7,3]]],axis=1)
b

ValueError: could not broadcast input array from shape (1,2) into shape (2,1)

In [52]:
a = np.arange(8).reshape(2,4)
b = np.insert(a,2,[[7,3]],axis=1)
b

array([[0, 1, 7, 2, 3],
       [4, 5, 3, 6, 7]])

In [53]:
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[7,3],axis=1)
b

array([[[0, 1],
        [2, 3],
        [7, 3]],

       [[4, 5],
        [6, 7],
        [7, 3]]])

In [54]:
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[[7,3]],axis=1)
b

array([[[0, 1],
        [2, 3],
        [7, 3]],

       [[4, 5],
        [6, 7],
        [7, 3]]])

In [55]:
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[[[7,3]]],axis=1)
b

array([[[0, 1],
        [2, 3],
        [7, 3]],

       [[4, 5],
        [6, 7],
        [7, 3]]])

In [56]:
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[[[[7,3]]]],axis=1)
b

array([[[0, 1],
        [2, 3],
        [7, 3]],

       [[4, 5],
        [6, 7],
        [7, 3]]])

In [57]:
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[[[[[7,3]]]]],axis=1)
b

array([[[0, 1],
        [2, 3],
        [7, 3]],

       [[4, 5],
        [6, 7],
        [7, 3]]])

In [58]:
# during insertion if we don't specify the axis, the array will be flattened
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[[[[7,3]]]])
b

ValueError: could not broadcast input array from shape (2,) into shape (1,)

In [59]:
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[[[7,3]]])
b

ValueError: could not broadcast input array from shape (2,) into shape (1,)

In [60]:
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[[7,3]])

b

ValueError: could not broadcast input array from shape (2,) into shape (1,)

In [61]:
# The array will be flattened whenever the array to be appended is 1D
a = np.arange(8).reshape(2,2,2)
b = np.insert(a,2,[7,3])
b

array([0, 1, 7, 3, 2, 3, 4, 5, 6, 7])

### Numpy.delete(arr,obj,axis= None)
- return array with subarrays along an axis deleted \
- for 1D array this returns those entries not returned by arra[obj]

In [64]:
a = np.arange(10).reshape(2,5)
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
np.delete(a,1,axis=1)

array([[0, 2, 3, 4],
       [5, 7, 8, 9]])

In [66]:
# with out axis it will be flattened
np.delete(a,1)

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

### Numpy Matrix
- import numpy.matlib
- numpy matrix is a subclass of numpy nd array


In [68]:
import numpy.matlib


In [69]:
# creating matrix by matlib.zeros() and matlib.ones()
a = np.matlib.zeros((2,3))
a

matrix([[0., 0., 0.],
        [0., 0., 0.]])

In [71]:
a = np.matlib.ones((2,3))
a

matrix([[1., 1., 1.],
        [1., 1., 1.]])

In [73]:
# creating a diagonal matrix using np.matlib.eye()
a = np.matlib.eye(3)
a

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [75]:
# transfer between arrays and matrix
a = np.array([[34,6,2],[4,5,1]])
b = np.mat(a)
a

array([[34,  6,  2],
       [ 4,  5,  1]])

In [76]:
b

matrix([[34,  6,  2],
        [ 4,  5,  1]])

In [77]:
# transfer a matrix to an array
b.getA()

array([[34,  6,  2],
       [ 4,  5,  1]])